In [32]:
import numpy as np

### 1. Создайте вектор с элементами от 12 до 42

In [33]:
vector1 = np.arange(12, 43)
vector1

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42])

### 2. Создайте вектор из нулей длины 12, но его пятый элемент должен быть равен 1

In [34]:
vector2 = np.zeros(12)
vector2[4] = 1
vector2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

### 3. Создайте матрицу (3, 3), заполненную от 0 до 8

In [35]:
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 4. Найдите все положительные числа в np.array([1,2,0,0,4,0])

In [36]:
array = np.array([1, 2, 0, 0, 4, 0])
array[array > 0]

array([1, 2, 4])

### 5. Умножьте матрицу размерности (5, 3) на (3, 2)

In [37]:
matrix1 = np.random.rand(5, 3)
matrix2 = np.random.rand(3, 2)
result = np.dot(matrix1, matrix2)
result

array([[1.09614556, 0.56583997],
       [0.91958241, 0.59979755],
       [1.41570602, 0.72276628],
       [0.83299979, 0.58002867],
       [1.14813328, 0.62073447]])

### 6. Создайте матрицу (10, 10) так, чтобы на границе были 0, а внутри 1

In [38]:
matrix_boundary = np.zeros((10, 10))
matrix_boundary[1:-1, 1:-1] = 1
matrix_boundary

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### 7. Создайте рандомный вектор и отсортируйте его

In [39]:
random_vector = np.random.rand(10)
np.sort(random_vector)

array([0.15892337, 0.34192033, 0.61685516, 0.71714068, 0.7358726 ,
       0.74008281, 0.74294222, 0.81935649, 0.87086457, 0.93059383])

### 8. Каков эквивалент функции enumerate для numpy массивов?

In [40]:
array = np.array([10, 20, 30, 32, 2, 1])
for index, value in np.ndenumerate(array):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 32
(4,) 2
(5,) 1


### 9. Создайте рандомную матрицу и выполните нормализацию столбцов

In [41]:
random_matrix = np.random.rand(5, 3)
normalized_matrix = (random_matrix - np.mean(random_matrix, axis=0))
normalized_matrix = normalized_matrix / np.std(normalized_matrix, axis=0)
normalized_matrix

array([[-0.84495277, -0.62705234,  1.81145698],
       [ 1.76838   ,  1.43790717, -0.42642864],
       [-0.288846  ,  0.97338317,  0.14224642],
       [ 0.3438101 , -0.89279249, -1.1821252 ],
       [-0.97839133, -0.89144551, -0.34514955]])

### 10. Для заданного числа найдите ближайший к нему элемент в векторе

In [42]:
number = 0.5
vector = np.random.rand(10)
print(vector)
closest_value = vector[np.abs(vector - number).argmin()]
closest_value

[0.0167902  0.85309889 0.62600782 0.8956776  0.87561567 0.00244427
 0.97149065 0.77922442 0.4447457  0.58205636]


0.4447457021835083

### 11. Найдите N наибольших значений в векторе

In [43]:
N = 3
vector = np.random.rand(10)
print(vector)
largest_values = vector[np.argsort(vector)[-N:]]
largest_values

[0.14238188 0.76165263 0.11091998 0.16031318 0.95304562 0.5596756
 0.48706775 0.16166331 0.19527356 0.16395541]


array([0.5596756 , 0.76165263, 0.95304562])