In [97]:
import pandas as pd
import numpy as np

A_path = 'A.dat'
b_path = 'b.dat'
A = np.matrix(pd.DataFrame(pd.read_csv(A_path, sep=' ', header=None), dtype=np.float64))
A = np.power(A, 2)
b = np.matrix(pd.read_csv(b_path, sep=' ', header=None), dtype=np.float64)
A

matrix([[1.23210000e-02, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 1.02030403e-06, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 1.75138782e-02]])

In [83]:
X = np.matrix(list(map(np.float64, input().split())))
X

matrix([[0.5],
        [0.1],
        [0.5]])

In [88]:
b

matrix([[2.5, 2.5, 2.5]])

In [100]:
print((np.dot(np.dot(X, A), b.T).astype(np.float64)).item())

0.03729385288450768
