In [1]:
import numpy as np

### 1. Создайте вектор с элементами от 12 до 42

In [2]:
vector1 = np.arange(12, 43)
vector1

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42])

### 2. Создайте вектор из нулей длины 12, но его пятый элемент должен быть равен 1

In [3]:
vector2 = np.zeros(12)
vector2[4] = 1
vector2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

### 3. Создайте матрицу (3, 3), заполненную от 0 до 8

In [4]:
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 4. Найдите все положительные числа в np.array([1,2,0,0,4,0])

In [5]:
array = np.array([1, 2, 0, 0, 4, 0])
array[array > 0]

array([1, 2, 4])

### 5. Умножьте матрицу размерности (5, 3) на (3, 2)

In [6]:
matrix1 = np.random.rand(5, 3)
matrix2 = np.random.rand(3, 2)
result = np.dot(matrix1, matrix2)
result

array([[0.32225529, 0.52206904],
       [0.81846318, 1.24864464],
       [0.69542363, 1.50482053],
       [0.54604066, 1.24144588],
       [0.87623487, 1.31295677]])

### 6. Создайте матрицу (10, 10) так, чтобы на границе были 0, а внутри 1

In [7]:
matrix_boundary = np.zeros((10, 10))
matrix_boundary[1:-1, 1:-1] = 1
matrix_boundary

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### 7. Создайте рандомный вектор и отсортируйте его

In [8]:
random_vector = np.random.rand(10)
np.sort(random_vector)

array([0.00282859, 0.23294829, 0.23555295, 0.40069012, 0.43913217,
       0.4444368 , 0.46082149, 0.54951145, 0.62763226, 0.78274228])

### 8. Каков эквивалент функции enumerate для numpy массивов?

In [9]:
array = np.array([10, 20, 30, 32, 2, 1])
for index, value in np.ndenumerate(array):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 32
(4,) 2
(5,) 1


### 9. Создайте рандомную матрицу и выполните нормализацию столбцов

In [10]:
random_matrix = np.random.rand(5, 3)
normalized_matrix = (random_matrix - np.mean(random_matrix, axis=0))
normalized_matrix = normalized_matrix / np.std(normalized_matrix, axis=0)
normalized_matrix

array([[-0.20188368, -1.10466309, -0.72526311],
       [ 0.51883227, -1.07861564, -1.53283415],
       [ 1.09042937,  0.53261919,  0.33387737],
       [ 0.4167269 ,  0.12880766,  1.24638771],
       [-1.82410486,  1.52185188,  0.67783219]])

### 10. Для заданного числа найдите ближайший к нему элемент в векторе

In [11]:
number = 0.5
vector = np.random.rand(10)
print(vector)
closest_value = vector[np.abs(vector - number).argmin()]
closest_value

[0.8251977  0.89499936 0.17350242 0.26201997 0.65725478 0.87279339
 0.42576559 0.47699786 0.9646253  0.48685284]


0.48685284029244835

### 11. Найдите N наибольших значений в векторе

In [12]:
N = 3
vector = np.random.rand(10)
print(vector)
largest_values = vector[np.argsort(vector)[-N:]]
largest_values

[0.08268683 0.7380664  0.57159374 0.90137837 0.65938238 0.64141147
 0.67578573 0.09683007 0.14258998 0.62327618]


array([0.67578573, 0.7380664 , 0.90137837])